import type { NextPage } from "next";

const Terms: NextPage = () => {
  return (
    <>
      <section className="relative py-20 bg-november-yellow">
        <div className="relative container px-4 mx-auto">
          <div className="max-w-4xl mx-auto text-center">
            <h2 className="mt-8 mb-6 lg:mb-10 text-5xl font-semibold font-heading">
              Privacy Policy
            </h2>
          </div>
        </div>
      </section>

      <section className="py-20">
        <div className="container px-4 mx-auto">
          <div className="max-w-4xl mx-auto">
            <div className="mb-12 text-md text-gray-700 text-justify">
              <p id="ce423e41-4b58-4730-817b-fa5e7771d01b" className="">
                Revised January 22, 2022
              </p>
              <br></br>{" "}
              <h1 id="69bcaa99-9ecb-4355-a39a-ab9c2e778602" className="">
                <strong>Introduction</strong>
              </h1>{" "}
              <br></br>
              <p id="7c0188e7-0b1c-4dcd-8a24-dcf24a9c9e40" className="">
                Welcome to <strong>Animo Ventures Inc.</strong>
              </p>
              <p id="68307112-ab86-4f54-b748-713750867d8f" className="">
                Animo Ventures Inc. (“us”, “we”, or “our”) operates{" "}
                <a
                  className="text-september-green"
                  href="https://getautumn.com"
                >
                  https://getautumn.com
                </a>{" "}
                and Autumn mobile application (hereinafter referred to as “
                <strong>Service</strong>”).
              </p>
              <p id="ea4750fc-b865-4171-af82-281dae008135" className="">
                Our Privacy Policy governs your visit to{" "}
                <a
                  className="text-september-green"
                  href="https://getautumn.com"
                >
                  https://www.getautumn.com
                </a>{" "}
                and Autumn web application, and explains how we collect,
                safeguard and disclose information that results from your use of
                our Service.
              </p>
              <p id="a0e80f56-e3a6-4f81-ae36-482421ffddfb" className="">
                We use your data to provide and improve Service. By using
                Service, you agree to the collection and use of information in
                accordance with this policy. Unless otherwise defined in this
                Privacy Policy, the terms used in this Privacy Policy have the
                same meanings as in our Terms and Conditions.
              </p>
              <p id="5acaa0e2-b48e-4f96-a1d2-49ab1d0cd4b7" className="">
                Our Terms and Conditions (“<strong>Terms</strong>”) govern all
                use of our Service and together with the Privacy Policy
                constitutes your agreement with us (“<strong>agreement</strong>
                ”).
              </p>
              <br></br>{" "}
              <h1 id="94088a13-d2a4-4dc5-a8fa-db16a1aff156" className="">
                <strong>Definitions</strong>
              </h1>{" "}
              <br></br>
              <p id="e9a92e94-831d-43de-83ab-b1cacc0ca0e7" className="">
                <strong>SERVICE </strong>means the{" "}
                <a
                  className="text-september-green"
                  href="https://www.getautumn.com"
                >
                  https://www.getautumn.com
                </a>{" "}
                website and Autumn web application operated by Health Science
                Inc.
              </p>
              <p id="09ea80b5-3404-4e25-a7ae-77a2b9c70e00" className="">
                <strong>PERSONAL DATA</strong> means data about a living
                individual who can be identified from those data (or from those
                and other information either in our possession or likely to come
                into our possession).
              </p>
              <p id="bcb242fe-01fb-43bf-a706-0054c516e45c" className="">
                <strong>USAGE DATA</strong> is data collected automatically
                either generated by the use of Service or from Service
                infrastructure itself (for example, the duration of a page
                visit).
              </p>
              <p id="94e336c5-8831-42bc-8863-4093c839c3e4" className="">
                <strong>COOKIES</strong> are small files stored on your device
                (computer or mobile device).
              </p>
              <p id="ef09df40-7d1c-4065-b27a-404d70195448" className="">
                <strong>DATA CONTROLLER</strong> means a natural or legal person
                who (either alone or jointly or in common with other persons)
                determines the purposes for which and the manner in which any
                personal data are, or are to be, processed. For the purpose of
                this Privacy Policy, we are a Data Controller of your data.
              </p>
              <p id="c7c70eb0-4d0b-4ec4-aa2b-aef889ecd36b" className="">
                <strong>DATA PROCESSORS (OR SERVICE PROVIDERS)</strong> means
                any natural or legal person who processes the data on behalf of
                the Data Controller. We may use the services of various Service
                Providers in order to process your data more effectively.
              </p>
              <p id="75fad6df-ee69-4bec-9e0a-a37f95b58f0c" className="">
                <strong>DATA SUBJECT</strong> is any living individual who is
                the subject of Personal Data.
              </p>
              <p id="26662c83-3afe-4b43-b43e-1107d26867dd" className="">
                <strong>THE USER</strong> is the individual using our Service.
                The User corresponds to the Data Subject, who is the subject of
                Personal Data.
              </p>
              <br></br>{" "}
              <h1 id="3ed41e55-c5a6-49bb-b38a-d04e30393845" className="">
                <strong>Information Collection and Use</strong>
              </h1>{" "}
              <br></br>
              <p id="ed86a183-6ce8-43e8-be86-7a8647e77b92" className="">
                We collect several different types of information for various
                purposes to provide and improve our Service to you.
              </p>
              <br></br>{" "}
              <h1 id="01e03dba-35ad-4105-9c30-c3aa857e2a27" className="">
                <strong>Types of Data Collected</strong>
              </h1>{" "}
              <br></br>
              <p id="81be7209-8390-47c9-a113-9df37d195d2e" className="">
                <strong>Personal Data</strong>
              </p>
              <p id="711dc8eb-795b-408f-ad56-3367cec30759" className="">
                While using our Service, we may ask you to provide us with
                certain personally identifiable information that can be used to
                contact or identify you (“<strong>Personal Data</strong>”).
                Personally identifiable information may include, but is not
                limited to:
              </p>
              <ol
                type="1"
                id="9f42b2db-c850-42bc-abe2-710cd65c73b7"
                className="numbered-list"
              >
                <li>Email address</li>
              </ol>
              <ol
                type="1"
                id="98b97825-334a-4fa5-b49c-7261d923c12e"
                className="numbered-list"
              >
                <li>First name and last name</li>
              </ol>
              <ol
                type="1"
                id="03776db0-8778-4b5f-a0ac-4ee20672322b"
                className="numbered-list"
              >
                <li>Phone number</li>
              </ol>
              <p id="9153c175-8a6d-4f2d-8c06-29d6a5911312" className="">
                We may use your Personal Data to contact you with newsletters,
                marketing or promotional materials and other information that
                may be of interest to you. You may opt out of receiving any, or
                all, of these communications from us by following the
                unsubscribe link.
              </p>
              <br />
              <p id="ee3ffccd-8f58-4df8-8491-94c46719a13c" className="">
                <strong>Usage Data</strong>
              </p>
              <p id="93fee3d3-5d33-4040-8753-c576d9c45114" className="">
                We may also collect information that your browser sends whenever
                you visit our Service or when you access Service by or through a
                mobile device (“<strong>Usage Data</strong>”).
              </p>
              <p id="3859c626-e418-4034-ab55-e2dfb2d2e699" className="">
                This Usage Data may include information such as your
                computer&#x27;s Internet Protocol address (e.g. IP address),
                browser type, browser version, the pages of our Service that you
                visit, the time and date of your visit, the time spent on those
                pages, unique device identifiers and other diagnostic data.
              </p>
              <p id="d68e78a2-ed97-4405-a406-4a1366c0361f" className="">
                When you access Service with a mobile device, this Usage Data
                may include information such as the type of mobile device you
                use, your mobile device unique ID, the IP address of your mobile
                device, your mobile operating system, the type of mobile
                Internet browser you use, unique device identifiers and other
                diagnostic data.
              </p>
              <br />
              <p id="29df863b-8a5f-40a2-a508-e8254ec459e9" className="">
                <strong>Tracking Cookies Data</strong>
              </p>
              <p id="5e74f9de-4271-41f1-a579-5a20e3bf06d7" className="">
                We use cookies and similar tracking technologies to track the
                activity on our Service and we hold certain information.
              </p>
              <p id="3c955b48-b60c-4b70-a2d4-8aee4990480b" className="">
                Cookies are files with a small amount of data which may include
                an anonymous unique identifier. Cookies are sent to your browser
                from a website and stored on your device. Other tracking
                technologies are also used such as beacons, tags and scripts to
                collect and track information and to improve and analyze our
                Service.
              </p>
              <p id="376f86c0-931e-48d4-898f-15029a1b00b2" className="">
                You can instruct your browser to refuse all cookies or to
                indicate when a cookie is being sent. However, if you do not
                accept cookies, you may not be able to use some portions of our
                Service.
              </p>
              <p id="3a1fc0d3-b9f8-49e1-84eb-20690705be0a" className="">
                Examples of Cookies we use:
              </p>
              <ol
                type="1"
                id="b38de4e0-b4b2-4fc0-bf3d-2e364d7cbe0b"
                className="numbered-list"
              >
                <li>
                  <strong>Session Cookies:</strong> We use Session Cookies to
                  operate our Service.
                </li>
              </ol>
              <ol
                type="1"
                id="98d9feb4-bb50-4337-8bd4-b097267ad1a7"
                className="numbered-list"
              >
                <li>
                  <strong>Preference Cookies</strong>: We use Preference Cookies
                  to remember your preferences and various settings.
                </li>
              </ol>
              <ol
                type="1"
                id="eabb2c2c-13be-448b-a78c-f8d0d12f99dd"
                className="numbered-list"
              >
                <li>
                  <strong>Security Cookies:</strong>We use Security Cookies for
                  security purposes.
                </li>
              </ol>
              <ol
                type="1"
                id="ddb1dec3-735b-4123-9d63-a6043af7f8d8"
                className="numbered-list"
              >
                <li>
                  <strong>Advertising Cookies:</strong>Advertising Cookies are
                  used to serve you with advertisements that may be relevant to
                  you and your interests.
                </li>
              </ol>
              <br></br>{" "}
              <h1 id="055d1804-b74c-4217-9eaa-849e9b8363c8" className="">
                <strong>Use of Data</strong>
              </h1>{" "}
              <br></br>
              <p id="dfd29f52-0a73-4578-a62e-a53274b29181" className="">
                Animo Ventures Inc. uses the collected data for various
                purposes:
              </p>
              <ol
                type="1"
                id="f6a9bb63-89d7-460f-93ac-fdece5dd6c30"
                className="numbered-list"
              >
                <li>to provide and maintain our Service;</li>
              </ol>
              <ol
                type="1"
                id="0d78cf81-f47d-4982-9198-7bcf6ac70f29"
                className="numbered-list"
              >
                <li>to notify you about changes to our Service;</li>
              </ol>
              <ol
                type="1"
                id="b1a3168b-6a14-4846-a398-de1a26dab4a3"
                className="numbered-list"
              >
                <li>
                  to allow you to participate in interactive features of our
                  Service when you choose to do so;
                </li>
              </ol>
              <ol
                type="1"
                id="e0d54013-f594-46c6-a9f1-4b9f33c3145a"
                className="numbered-list"
              >
                <li>to provide customer support;</li>
              </ol>
              <ol
                type="1"
                id="6344eb8d-b3e5-40e0-a5a1-1054a7b23894"
                className="numbered-list"
              >
                <li>
                  to gather analysis or valuable information so that we can
                  improve our Service;
                </li>
              </ol>
              <ol
                type="1"
                id="5d03a447-c71d-4e2d-ac7e-93910f63a2a8"
                className="numbered-list"
              >
                <li>to monitor the usage of our Service;</li>
              </ol>
              <ol
                type="1"
                id="62e82ba7-573e-4726-b306-46dbc101811e"
                className="numbered-list"
              >
                <li>to detect, prevent and address technical issues;</li>
              </ol>
              <ol
                type="1"
                id="5a5b6e96-b163-49d8-b938-8f2c396464a2"
                className="numbered-list"
              >
                <li>to fulfill any other purpose for which you provide it;</li>
              </ol>
              <ol
                type="1"
                id="024644ec-0c28-44bc-a488-0f1e650bc67a"
                className="numbered-list"
              >
                <li>
                  to carry out our obligations and enforce our rights arising
                  from any contracts entered into between you and us, including
                  for billing and collection;
                </li>
              </ol>
              <ol
                type="1"
                id="8086fa72-463b-4476-87c1-b48b204f1cc8"
                className="numbered-list"
              >
                <li>
                  to provide you with notices about your account and/or
                  subscription, including expiration and renewal notices,
                  email-instructions, etc.;
                </li>
              </ol>
              <ol
                type="1"
                id="811d102f-549e-4be3-9b8f-088c32c3c9cd"
                className="numbered-list"
              >
                <li>
                  to provide you with news, special offers and general
                  information about other goods, services and events which we
                  offer that are similar to those that you have already
                  purchased or enquired about unless you have opted not to
                  receive such information;
                </li>
              </ol>
              <ol
                type="1"
                id="062f4850-2b98-4a14-8a9d-1c7c90c852e1"
                className="numbered-list"
              >
                <li>
                  in any other way we may describe when you provide the
                  information;
                </li>
              </ol>
              <ol
                type="1"
                id="b9345ebd-826c-43ab-a6be-c02ad13f47b9"
                className="numbered-list"
              >
                <li>for any other purpose with your consent.</li>
              </ol>
              <br></br>{" "}
              <h1 id="94eea2a5-3117-4b81-8e4d-1560b38d9733" className="">
                <strong>Retention of Data</strong>
              </h1>{" "}
              <br></br>
              <p id="0f984f24-9dd4-4bda-b9b1-f1ab1b9e0346" className="">
                We will retain your Personal Data only for as long as is
                necessary for the purposes set out in this Privacy Policy. We
                will retain and use your Personal Data to the extent necessary
                to comply with our legal obligations (for example, if we are
                required to retain your data to comply with applicable laws),
                resolve disputes, and enforce our legal agreements and policies.
              </p>
              <p id="2a082655-ac19-4d5b-a688-f8fc265a4c65" className="">
                We will also retain Usage Data for internal analysis purposes.
                Usage Data is generally retained for a shorter period, except
                when this data is used to strengthen the security or to improve
                the functionality of our Service, or we are legally obligated to
                retain this data for longer time periods.
              </p>
              <br></br>{" "}
              <h1 id="0c92bb12-2b18-4dff-8fcb-639e037a3e32" className="">
                <strong>Transfer of Data</strong>
              </h1>{" "}
              <br></br>
              <p id="658812dc-e5d1-4ed1-bf20-f63ae8478837" className="">
                Your information, including Personal Data, may be transferred to
                - and maintained on - computers located outside of your state,
                province, country or other governmental jurisdiction where the
                data protection laws may differ from those of your jurisdiction.
              </p>
              <p id="2470e13b-82a6-489b-a690-2daa5ba06328" className="">
                If you are located outside the United States and choose to
                provide information to us, please note that we transfer the
                data, including Personal Data, to the United States and process
                it there.
              </p>
              <p id="4fcad768-a586-44a0-8e0f-c0b818c87cc6" className="">
                Your consent to this Privacy Policy followed by your submission
                of such information represents your agreement to that transfer.
              </p>
              <p id="3a525a7d-b57c-4cdd-8d45-b8a2fddbf7f9" className="">
                Animo Ventures Inc. will take all the steps reasonably necessary
                to ensure that your data is treated securely and in accordance
                with this Privacy Policy and no transfer of your Personal Data
                will take place to an organization or a country unless there are
                adequate controls in place including the security of your data
                and other personal information.
              </p>
              <br></br>{" "}
              <h1 id="f0a7e389-3aca-4097-8422-269e3344a4dd" className="">
                <strong>Disclosure of Data</strong>
              </h1>{" "}
              <br></br>
              <p id="c07b1634-ce54-4e50-9e7f-3f40b7f3d8f5" className="">
                We may disclose personal information that we collect, or you
                provide:
              </p>
              <ol
                type="1"
                id="030c3918-472e-44ec-bf1d-23fb4badecc8"
                className="numbered-list"
              >
                <li>
                  <strong>Disclosure for Law Enforcement.</strong>Under certain
                  circumstances, we may be required to disclose your Personal
                  Data if required to do so by law or in response to valid
                  requests by public authorities.
                </li>
              </ol>
              <ol
                type="1"
                id="a9a137ac-dd43-4b90-be97-b510d9917dfe"
                className="numbered-list"
              >
                <li>
                  <strong>Business Transaction.</strong>If we or our
                  subsidiaries are involved in a merger, acquisition or asset
                  sale, your Personal Data may be transferred.
                </li>
              </ol>
              <ol
                type="1"
                id="b9b1cea0-37d0-4570-9a4f-30c3dcbd1220"
                className="numbered-list"
              >
                <li>
                  <strong>
                    Other cases. We may disclose your information also:
                  </strong>
                </li>
              </ol>
              <ol
                type="1"
                id="8174fa3b-a7b2-44e6-a45e-6c254f946394"
                className="numbered-list"
              >
                <li>to our subsidiaries and affiliates;</li>
              </ol>
              <ol
                type="1"
                id="19f97481-471c-443c-8a1c-09993bfdb558"
                className="numbered-list"
              >
                <li>
                  to contractors, service providers, and other third parties we
                  use to support our business;
                </li>
              </ol>
              <ol
                type="1"
                id="d9d06e61-0a30-41d4-a2f2-2112030469db"
                className="numbered-list"
              >
                <li>to fulfill the purpose for which you provide it;</li>
              </ol>
              <ol
                type="1"
                id="611d1cb5-7aec-4c5b-9b0e-54d9327761f8"
                className="numbered-list"
              >
                <li>
                  for the purpose of including your company&apos;s logo on our
                  website;
                </li>
              </ol>
              <ol
                type="1"
                id="28a87d59-2d33-4902-a156-6878a5e20c9e"
                className="numbered-list"
              >
                <li>
                  for any other purpose disclosed by us when you provide the
                  information;
                </li>
              </ol>
              <ol
                type="1"
                id="337d07dc-aca1-4424-b04a-e2da9f3e84c9"
                className="numbered-list"
              >
                <li>with your consent in any other cases;</li>
              </ol>
              <ol
                type="1"
                id="474dd9a6-1638-4151-b37e-4a5f124fc5f3"
                className="numbered-list"
              >
                <li>
                  if we believe disclosure is necessary or appropriate to
                  protect the rights, property, or safety of the Company, our
                  customers, or others.
                </li>
              </ol>
              <br></br>{" "}
              <h1 id="2b891e92-99c4-489f-8a0c-e9a4a0411e95" className="">
                <strong>Security of Data</strong>
              </h1>{" "}
              <br></br>
              <p id="c900298f-b269-4e5a-b71e-72e70de00c36" className="">
                The security of your data is important to us but remember that
                no method of transmission over the Internet or method of
                electronic storage is 100% secure. While we strive to use
                commercially acceptable means to protect your Personal Data, we
                cannot guarantee its absolute security.
              </p>
              <br></br>{" "}
              <h1 id="7d947183-0cba-408f-962f-bdf71602df32" className="">
                <strong>
                  Your Data Protection Rights Under General Data Protection
                  Regulation (GDPR)
                </strong>
              </h1>{" "}
              <br></br>
              <p id="1b4bcc58-3ae4-47ce-b100-5749b5fac50b" className="">
                If you are a resident of the European Union (EU) and European
                Economic Area (EEA), you have certain data protection rights,
                covered by GDPR. See more at{" "}
                <a
                  className="text-september-green"
                  href="https://eur-lex.europa.eu/eli/reg/2016/679/oj"
                >
                  https://eur-lex.europa.eu/eli/reg/2016/679/oj
                </a>
              </p>
              <p id="d0a6340f-ac8f-4cec-9f15-1c2bfb441aa7" className="">
                We aim to take reasonable steps to allow you to correct, amend,
                delete, or limit the use of your Personal Data.
              </p>
              <p id="fa672e25-b6d0-48af-8a7a-bbc9994bc7d9" className="">
                If you wish to be informed what Personal Data we hold about you
                and if you want it to be removed from our systems, please email
                us at{" "}
                <a
                  className="text-september-green"
                  href="mailto:support@help@getautumn.com"
                >
                  help@getautumn.com
                </a>
                .
              </p>
              <p id="339d2feb-016d-4bc5-8609-0d831a885fe4" className="">
                In certain circumstances, you have the following data protection
                rights:
              </p>
              <ol
                type="1"
                id="26e927a1-4fe4-49b6-be71-56d435dfae54"
                className="numbered-list"
              >
                <li>
                  the right to access, update or to delete the information we
                  have on you;
                </li>
              </ol>
              <ol
                type="1"
                id="55a948fa-2abf-4ff2-8d48-0a79560a3a92"
                className="numbered-list"
              >
                <li>
                  the right of rectification. You have the right to have your
                  information rectified if that information is inaccurate or
                  incomplete;
                </li>
              </ol>
              <ol
                type="1"
                id="16e033ac-e5f5-4240-aff9-7858c7909880"
                className="numbered-list"
              >
                <li>
                  the right to object. You have the right to object to our
                  processing of your Personal Data;
                </li>
              </ol>
              <ol
                type="1"
                id="1ed93317-70e5-48bf-a11d-06a99f5048f5"
                className="numbered-list"
              >
                <li>
                  the right of restriction. You have the right to request that
                  we restrict the processing of your personal information;
                </li>
              </ol>
              <ol
                type="1"
                id="c3424b22-2ec2-4ee7-ab7b-553deea6bddc"
                className="numbered-list"
              >
                <li>
                  the right to data portability. You have the right to be
                  provided with a copy of your Personal Data in a structured,
                  machine-readable and commonly used format;
                </li>
              </ol>
              <ol
                type="1"
                id="cd1fdcba-30ac-4cd8-8214-4d7df70d3e1f"
                className="numbered-list"
              >
                <li>
                  the right to withdraw consent. You also have the right to
                  withdraw your consent at any time where we rely on your
                  consent to process your personal information;
                </li>
              </ol>
              <p id="5ee07bd1-2a4f-4806-9aff-8a18a4ec9d6e" className="">
                Please note that we may ask you to verify your identity before
                responding to such requests. Please note, we may not be able to
                provide Service without some necessary data.
              </p>
              <p id="efebe223-14e5-4e2b-b252-35b630a71044" className="">
                You have the right to complain to a Data Protection Authority
                about our collection and use of your Personal Data. For more
                information, please contact your local data protection authority
                in the European Economic Area (EEA).
              </p>
              <br></br> <br></br>{" "}
              <h1 id="a01ab9ab-54ff-48ae-a5dc-db10c8550674" className="">
                <strong>Service Providers</strong>
              </h1>{" "}
              <br></br>
              <p id="63ffb1d1-05a8-4747-a696-0a4f6eee05db" className="">
                We may employ third party companies and individuals to
                facilitate our Service (“<strong>Service Providers</strong>”),
                provide Service on our behalf, perform Service-related services
                or assist us in analyzing how our Service is used.
              </p>
              <p id="986c9595-6d34-404c-9b7e-64c2e975edc1" className="">
                These third parties have access to your Personal Data only to
                perform these tasks on our behalf and are obligated not to
                disclose or use it for any other purpose.
              </p>
              <br></br>{" "}
              <h1 id="56c61421-d496-439c-9ed1-027fd4f75009" className="">
                <strong>Analytics</strong>
              </h1>{" "}
              <br></br>
              <p id="db9d65e7-a2dc-489c-9a06-a03568a69e56" className="">
                We may use third-party Service Providers to monitor and analyze
                the use of our Service.
              </p>
              <br />
              <p id="cf9e9204-15a9-4934-b01b-3e5283546381" className="">
                <strong>Google Analytics</strong>
              </p>
              <p id="cddd9db7-e21a-4f87-8338-e2ec947f44e7" className="">
                Google Analytics is a web analytics service offered by Google
                that tracks and reports website traffic. Google uses the data
                collected to track and monitor the use of our Service. This data
                is shared with other Google services. Google may use the
                collected data to contextualize and personalize the ads of its
                own advertising network.
              </p>
              <p id="15829216-e5b2-4da8-87db-2dca41a32811" className="">
                For more information on the privacy practices of Google, please
                visit the Google Privacy Terms web page:{" "}
                <a
                  className="text-september-green"
                  href="https://policies.google.com/privacy?hl=en"
                >
                  https://policies.google.com/privacy?hl=en
                </a>
              </p>
              <p id="b97c01b3-a9e7-46c4-a89a-ba321d9c55ce" className="">
                We also encourage you to review Google&#x27;s policy for
                safeguarding your data:{" "}
                <a
                  className="text-september-green"
                  href="https://support.google.com/analytics/answer/6004245"
                >
                  https://support.google.com/analytics/answer/6004245
                </a>
                .
              </p>
              <br />
              <p id="6b7fd229-fdb0-4b61-ab5c-127964834105" className="">
                <strong>Segment.io</strong>
              </p>
              <p id="1367ecff-6dbd-46c2-8141-211b7753ebd1" className="">
                Segment.io is a web traffic analysis tool. You can read the
                Privacy Policy for Segment.io here:{" "}
                <a
                  className="text-september-green"
                  href="https://segment.com/legal/privacy/"
                >
                  https://segment.com/legal/privacy/
                </a>
                .
              </p>
              <br />
              <p id="4258f02b-4f80-4d05-bd62-cd5a2face440" className="">
                <strong>Mixpanel</strong>
              </p>
              <p id="8c6006de-bf3d-45c5-a619-b19dd0856d5b" className="">
                Mixpanel is provided by Mixpanel Inc.
              </p>
              <p id="da1a5845-0451-4b86-81c0-e5d20245da12" className="">
                You can prevent Mixpanel from using your information for
                analytics purposes by opting-out. To opt-out of Mixpanel
                service, please visit this page:{" "}
                <a
                  className="text-september-green"
                  href="https://mixpanel.com/optout/"
                >
                  https://mixpanel.com/optout/
                </a>
              </p>
              <p id="eea268c3-1fb4-499d-97de-00c3794752a3" className="">
                For more information on what type of information Mixpanel
                collects, please visit the Terms of Use page of Mixpanel:{" "}
                <a
                  className="text-september-green"
                  href="https://mixpanel.com/terms/"
                >
                  https://mixpanel.com/terms/
                </a>
              </p>
              <br></br>{" "}
              <h1 id="f6849b99-3dd6-45a6-a4e4-9114b202ae09" className="">
                <strong>CI/CD tools</strong>
              </h1>{" "}
              <p id="7465c745-e734-462d-aa2d-12ac65077477" className="">
                We may use third-party Service Providers to automate the
                development process of our Service.
              </p>
              <br />
              <p id="17733f42-34f3-42e4-bc01-60e11d8375e0" className="">
                <strong>Gitlab</strong>
              </p>
              <p id="b0b7b3e2-0259-4888-9071-336de70ffc4e" className="">
                Gitlab is provided by Gitlab, Inc.
              </p>
              <p id="ec731acc-2dff-47c5-b941-d01a16ed3188" className="">
                Gitlab is a development platform to host and review code, manage
                projects, and build software.
              </p>
              <p id="a4015a38-2175-4019-8729-de768783db54" className="">
                For more information on what data GitHub collects for what
                purpose and how the protection of the data is ensured, please
                visit Gitlab Privacy Policy page:{" "}
                <a
                  className="text-september-green"
                  href="https://about.gitlab.com/privacy/"
                >
                  https://about.gitlab.com/privacy/.
                </a>
              </p>
              <br></br>{" "}
              <h1 id="afdc9c43-4199-4f4e-924f-72d242b29290" className="">
                <strong>Behavioral Remarketing</strong>
              </h1>{" "}
              <p id="d215fb98-5757-4507-bb3a-945abdc514a3" className="">
                Animo Ventures Inc. uses remarketing services to advertise on
                third party websites to you after you visited our Service. We
                and our third-party vendors use cookies to inform, optimise and
                serve ads based on your past visits to our Service.
              </p>
              <br />
              <p id="88d08b2a-8671-47ae-9298-be5773a0aedd" className="">
                <strong>Google Ads (AdWords)</strong>
              </p>
              <p id="6373e2c0-e45f-4a8a-8480-4b7c2a2a1fd2" className="">
                Google Ads (AdWords) remarketing service is provided by Google
                Inc.
              </p>
              <p id="e529c762-29e5-4f9f-bae7-759e08256271" className="">
                You can opt-out of Google Analytics for Display Advertising and
                customize the Google Display Network ads by visiting the Google
                Ads Settings page:{" "}
                <a
                  className="text-september-green"
                  href="https://www.google.com/settings/ads"
                >
                  https://www.google.com/settings/ads
                </a>
              </p>
              <p id="17bdae72-57c0-419c-b97c-1d2e859a285f" className="">
                Google also recommends installing the Google Analytics Opt-out
                Browser Add-on -
                <a
                  className="text-september-green"
                  href="https://tools.google.com/dlpage/gaoptout"
                >
                  https://tools.google.com/dlpage/gaoptout
                </a>{" "}
                - for your web browser. Google Analytics Opt-out Browser Add-on
                provides visitors with the ability to prevent their data from
                being collected and used by Google Analytics.
              </p>
              <p id="235db361-18b8-42b5-a308-0101619cdeba" className="">
                For more information on the privacy practices of Google, please
                visit the Google Privacy Terms web page:{" "}
                <a
                  className="text-september-green"
                  href="https://policies.google.com/privacy?hl=en"
                >
                  https://policies.google.com/privacy?hl=en
                </a>
              </p>
              <br></br>{" "}
              <h1 id="85ced9ae-09ff-40f0-a4f3-3df59fe64556" className="">
                <strong>Payments</strong>
              </h1>{" "}
              <br></br>
              <p id="aaa71814-f041-4ce6-bb8d-adadcaf65edc" className="">
                We may provide paid products and/or services within Service. In
                that case, we use third-party services for payment processing
                (e.g. payment processors).
              </p>
              <p id="a042939a-f453-4ac2-b73b-d919b10da579" className="">
                We will not store or collect your payment card details. That
                information is provided directly to our third-party payment
                processors whose use of your personal information is governed by
                their Privacy Policy. These payment processors adhere to the
                standards set by PCI-DSS as managed by the PCI Security
                Standards Council, which is a joint effort of brands like Visa,
                Mastercard, American Express and Discover. PCI-DSS requirements
                help ensure the secure handling of payment information.
              </p>
              <p id="6619ebc0-aaed-4890-94da-0f5a62738f15" className="">
                The payment processors we work with are:
              </p>
              <br></br>
              <p id="4c2e7eb1-4054-4427-b670-e2d164a93a2d" className="">
                <strong>Stripe:</strong>
              </p>
              <p id="1377aa15-8727-46c6-857a-4179d643daae" className="">
                Their Privacy Policy can be viewed at:{" "}
                <a
                  className="text-september-green"
                  href="https://stripe.com/us/privacy"
                >
                  https://stripe.com/us/privacy
                </a>
              </p>
              <br></br>{" "}
              <h1 id="8f9d11fa-3345-4c64-96e5-f6008ac3faa4" className="">
                <strong>Links to Other Sites</strong>
              </h1>{" "}
              <br></br>
              <p id="42c4881a-ffb5-4354-b290-32c49c6f7ec3" className="">
                Our Service may contain links to other sites that are not
                operated by us. If you click a third party link, you will be
                directed to that third party&#x27;s site. We strongly advise you
                to review the Privacy Policy of every site you visit.
              </p>
              <p id="b567fdb6-2e01-4b35-a9fd-25996bf02892" className="">
                We have no control over and assume no responsibility for the
                content, privacy policies or practices of any third party sites
                or services.
              </p>
              <br></br>{" "}
              <h1 id="54ba4156-001d-4f27-99f7-5fa5a2d395cf" className="">
                <strong>Children&#x27;s Privacy</strong>
              </h1>{" "}
              <br></br>
              <p id="17a7e78a-ed1f-48db-871b-c023eb630e35" className="">
                Our Services are not intended for use by children under the age
                of 18 (“<strong>Child</strong>” or “<strong>Children</strong>”).
              </p>
              <p id="3304594c-a303-437e-bf5b-1a6bc127a6c2" className="">
                We do not knowingly collect personally identifiable information
                from Children under 18. If you become aware that a Child has
                provided us with Personal Data, please contact us. If we become
                aware that we have collected Personal Data from Children without
                verification of parental consent, we take steps to remove that
                information from our servers.
              </p>
              <br></br>{" "}
              <h1 id="c0dbe515-d421-420e-89e5-432af11b060d" className="">
                <strong>Changes to This Privacy Policy</strong>
              </h1>{" "}
              <br></br>
              <p id="126692bd-0199-4434-9f43-a2e796fbf55d" className="">
                We may update our Privacy Policy from time to time. We will
                notify you of any changes by posting the new Privacy Policy on
                this page.
              </p>
              <p id="b3ec039d-7832-47c0-bc34-cf3bc83bbe9c" className="">
                We will let you know via email and/or a prominent notice on our
                Service, prior to the change becoming effective and update
                “effective date” at the top of this Privacy Policy.
              </p>
              <p id="8781661f-2acd-4031-9d6b-a184f23feb0b" className="">
                You are advised to review this Privacy Policy periodically for
                any changes. Changes to this Privacy Policy are effective when
                they are posted on this page.
              </p>
              <br></br>{" "}
              <h1 id="e254cb85-065f-48c0-84b4-fad8caa6fe94" className="">
                <strong>Contact Us</strong>
              </h1>{" "}
              <br></br>
              <p id="1e23355f-7a44-4093-83dc-d498560da2e8" className="">
                If you have any questions about this Privacy Policy, please
                contact us:
              </p>
              <p id="648d35f7-5376-4558-b1e2-253f85a76ec5" className="">
                By email:{" "}
                <a
                  className="text-september-green"
                  href="mailto:help@getautumn.com"
                >
                  help@getautumn.com
                </a>
                .
              </p>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default Terms;
